In [1]:
from google.colab import files
files.upload()

Saving 3 parameters subset.csv to 3 parameters subset.csv


{'3 parameters subset.csv': b'long,lat,ndvi,mdbi,elevation,lst\r\n82.95900306,25.33350704,0.331832,-0.491238,82,32.01352026\r\n82.95930099,25.33350307,0.215443,-0.524814,82,32.36835548\r\n82.95959892,25.33349911,0.177456,-0.537487,81,32.54880209\r\n82.95989685,25.33349515,0.235215,-0.529626,82,32.57442123\r\n82.96019478,25.33349118,0.271205,-0.481921,83,32.47863827\r\n82.96049271,25.33348722,0.287452,-0.481914,83,32.15141829\r\n82.96079064,25.33348325,0.27127,-0.47536,82,31.71320685\r\n82.96108857,25.33347928,0.254709,-0.472948,80,31.44609609\r\n82.9613865,25.33347532,0.286346,-0.468519,79,31.50807136\r\n82.96168443,25.33347135,0.32535,-0.485666,79,31.72776406\r\n82.96198236,25.33346738,0.300528,-0.480662,81,32.04264067\r\n82.96228029,25.33346341,0.273058,-0.475065,81,32.39586936\r\n82.96257822,25.33345944,0.185699,-0.467402,80,32.76214878\r\n82.96287614,25.33345547,0.160526,-0.463138,80,33.03362771\r\n82.96317407,25.3334515,0.219147,-0.487896,79,33.18472664\r\n82.963472,25.33344753,0.

In [2]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler



In [ ]:
data=pd.read_csv('3parameters.csv',encoding='latin1')
df=pd.DataFrame(data,columns=['ndvi','mdbi','elevation','lst'])
display(df)
print('ndvi_max',df.ndvi.max())
print('mdbi_max',df.mdbi.max())
print('elevation_max',df.elevation.max())
print('lst_max',df.lst.max())
target_column=df.lst
target_column=target_column/target_column.max()
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
print(df[predictors])
df.describe().transpose()

FileNotFoundError: ignored

In [ ]:
X = df[predictors].values
y = target_column
print(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=2)
print(X_train.shape); print(X_test.shape)
print(X_train)

0        0.806158
1        0.815094
2        0.819638
3        0.820283
4        0.817871
           ...   
49059    0.783464
49060    0.775910
49061    0.770733
49062    0.769661
49063    0.772445
Name: lst, Length: 49064, dtype: float64
(34344, 4)
(14720, 4)
[[0.43875067 2.91773526 0.83673469 0.80270088]
 [0.63370434 3.14849583 0.84693878 0.82405617]
 [0.48197438 3.02072108 0.84693878 0.83709054]
 ...
 [0.69520128 3.03538416 0.86734694 0.86192509]
 [0.23871458 2.73231574 0.83673469 0.83011007]
 [0.17590737 2.55929382 0.82653061 0.86665393]]


In [ ]:


mlp = MLPRegressor(hidden_layer_sizes=20, activation='relu', solver='adam', alpha=0.001,max_iter=900,random_state=50,learning_rate_init=0.01)
model=mlp.fit(X_train,y_train)
print(model)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
predict_y=mlp.predict(X)
k=predict_y*39.7112124
print(k)
df['k']=k
display(df['k'])
print('Mean_Squared_Error',mean_squared_error(y_test,predict_test))
print('Mean_Absolute_Error',mean_absolute_error(y_test,predict_test))


MLPRegressor(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=20, learning_rate='constant',
             learning_rate_init=0.01, max_fun=15000, max_iter=900, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=50, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)
[32.04275984 32.4278129  32.63694423 ... 30.81886477 30.79098501
 30.88638046]


0        32.042760
1        32.427813
2        32.636944
3        32.609261
4        32.501436
           ...    
49059    31.313480
49060    31.017969
49061    30.818865
49062    30.790985
49063    30.886380
Name: k, Length: 49064, dtype: float64

Mean_Squared_Error 2.6201853803181174e-06
Mean_Absolute_Error 0.0011535864160293627


In [ ]:
data2=pd.read_csv('3parameters.csv',encoding='latin1')
df=pd.DataFrame(data2,columns=['ndvi','mdbi','elevation','lst'])
display(df)
df['k'] = k
display(df['k'])
print(k.min())
print(k.max())
dfout1 = pd.merge(df,df['k'].dropna().to_frame(),how = 'left',left_index = True,   right_index = True)
from google.colab import files
dfout1.to_csv('data2.csv')
files.download('data2.csv')

ndvi      mdbi  elevation        lst
0      0.331832 -0.491238         82  32.013520
1      0.215443 -0.524814         82  32.368355
2      0.177456 -0.537487         81  32.548802
3      0.235215 -0.529626         82  32.574421
4      0.271205 -0.481921         83  32.478638
...         ...       ...        ...        ...
49059  0.309831 -0.495693         73  31.112314
49060  0.315600 -0.494288         74  30.812310
49061  0.330823 -0.488255         74  30.606739
49062  0.310705 -0.482848         74  30.564160
49063  0.305134 -0.481042         75  30.674745

[49064 rows x 4 columns]

0        32.009700
1        32.433181
2        32.627368
3        32.580726
4        32.491622
           ...    
49059    31.278714
49060    31.013256
49061    30.822743
49062    30.816383
49063    30.917866
Name: k, Length: 49064, dtype: float64

29.73951672009643
38.9185502449271


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>